{{- if .Values.scavenging.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eventstoredb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstoredb.name" . }}
    helm.sh/chart: {{ include "eventstoredb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: scavenging
{{- end }}
