apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventstoredb.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstoredb.name" . }}
    helm.sh/chart: {{ include "eventstoredb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: admin
data:
  nginx.conf: |
    server {
        listen {{ .Values.extHttpPort }};
        # set a variable so nginx will not check if host is available on startup
        # ref: https://stackoverflow.com/a/43341304/2108162
        resolver {{ .Values.admin.dnsResolver }}.kube-system.svc.cluster.local valid=5s;
        set $eventstoredb http://{{ include "eventstoredb.dns" . }}:{{ .Values.extHttpPort }};
        location = /_liveness {
            add_header Content-Type text/plain;
            return 200 'ok';
        }
        location = /_readiness {
            proxy_pass          $eventstoredb/stats;
        }
        location / {
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_set_header    Host      $http_host;
            proxy_pass          $eventstoredb;
        }
    }
