apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventstoredb.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstoredb.name" . }}
    helm.sh/chart: {{ include "eventstoredb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
data:
  ## Set Insecure 
  EVENTSTORE_INSECURE: {{ quote .Values.insecure }}
  ## Set  projections 
  EVENTSTORE_RUN_PROJECTIONS: {{ quote .Values.runProjections }}
  ## Set standard projections 
  EVENTSTORE_START_STANDARD_PROJECTIONS: {{ quote .Values.startStandardProections }}
  ## Set stats to db
  EVENTSTORE_WRITE_STATS_TO_DB: {{ quote .Values.enableStatsWriteToDb }}
  ## Internal TCP port.
  EVENTSTORE_INT_TCP_PORT: {{ quote .Values.intTcpPort }}
  ## External TCP port.
  EVENTSTORE_EXT_TCP_PORT: {{ quote .Values.extTcpPort }}
  ## Internal HTTP port.
  EVENTSTORE_INT_HTTP_PORT: {{ quote .Values.intHttpPort }}
  ## External HTTP port.
  EVENTSTORE_EXT_HTTP_PORT: {{ quote .Values.extHttpPort }}
  ## The number of nodes in the cluster. 
  EVENTSTORE_CLUSTER_SIZE: {{ quote .Values.clusterSize }}
  ## DNS name from which other nodes can be discovered. 
  EVENTSTORE_CLUSTER_DNS: {{ include "eventstoredb.dns" . }}
  ## Port on which nodes should gossip
  EVENTSTORE_CLUSTER_GOSSIP_PORT: {{ quote .Values.intHttpPort }}
  ## The amount of drift, in ms, between clocks on nodes allowed before gossip is rejected.
  EVENTSTORE_GOSSIP_ALLOWED_DIFFERENCE_MS: {{ quote .Values.gossipAllowedDiffMs }}
  ## Whether or not to add interface prefixes.
  EVENTSTORE_ADD_INTERFACE_PREFIXES: "False"
  ## The prefixes that the internal HTTP server should respond to. 
  EVENTSTORE_INT_HTTP_PREFIXES: "http://*:{{ .Values.intHttpPort }}/"
  ## The prefixes that the external HTTP server should respond to. 
  EVENTSTORE_EXT_HTTP_PREFIXES: "http://*:{{ .Values.extHttpPort }}/"
  # Note: changing `Values.eventStoreConfig` won't change the configmap 
  # checksum and so won't make the pods restart
  {{- range $setting, $option := .Values.eventStoreConfig }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
